autobim/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import signin, signout
from home.views import dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='home'),
    
    path('login/', signin, name='login'),
    path('logout/', signout, name='logout'),

    path('users/', include('users.urls')),
    path('design-check/', include('design_health.urls')),
    path('tidp/', include('tidp.urls')),
]

tidp/urls.py
from django.urls import path

from . import views

app_name = 'tidp'

urlpatterns = [
    path('roles/', views.role_list_view, name='roles'),
    path('roles/<int:pk>/update/', views.RoleUpdateView.as_view(), name="role-update"),
    path('roles/<int:pk>/delete/', views.RoleDeleteView.as_view(), name="role-delete"),

    path('company/list/', views.CompanyListView.as_view(),
       name='company-list'),
    path('company/create/', views.CompanyCreateView.as_view(),
        name='create-company'),
    path('company/<int:pk>/update/', views.CompanyUpdateView.as_view(), name="company-update"),
    path('company/<int:pk>/delete/', views.CompanyDeleteView.as_view(), name="company-delete"),

    path('projects/', views.ManageProjects.as_view(), name='projects'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/manage/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('project/<int:pk>/lmanage/', views.ProjectDetailLeaderView.as_view(), name='project-detail-leader'),
    path('projects/<int:pk>/update/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('projects/submit-to-lead/', views.ProjectSubmitToLeadView.as_view(), name='project-submit-to-lead'),
    path('projects/role-status-update/<int:projectrole_id>/', views.RoleStatusUpdateView.as_view(), name='role-status-update'),

    path('project-discipline/', views.DisciplineListView.as_view(), name='project-discipline'),
    path('project-discipline/create/', views.DisciplineCreateView.as_view(), name='discipline-create'),
    path('discipline/<int:pk>/update/', views.DisciplineUpdateView.as_view(), name='update-discipline'),
    path('discipline/<int:pk>/delete/', views.DisciplineDeleteView.as_view(), name='delete-discipline'),

    path('discipline-categories/', views.DisciplineCategoryListView.as_view(), name='project-discipline-categories'),
    path('discipline-categories/create/', views.DisciplineCategoryCreateView.as_view(), name='discipline-category-create'),
    path('discipline-categories/<int:pk>/update/', views.DisciplineCategoryUpdateView.as_view(), name='update-discipline-category'),
    path('discipline-categories/<int:pk>/delete/', views.DisciplineCategoryDeleteView.as_view(), name='delete-discipline-category'),

    path('tasks/', views.TaskListView.as_view(), name='tasks'),
    path('tasks/create/', views.TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:pk>/update/', views.TaskUpdateView.as_view(), name="task-update"),
    path('tasks/<int:pk>/delete/', views.TaskDeleteView.as_view(), name="task-delete"),

    path('tasktype/', views.TaskTypeView.as_view(), name='tasktypes'),
    path('tasktype/create/', views.TaskTypeCreateView.as_view(), name='tasktype-create'),
    path('tasktype/<int:pk>/update/', views.TaskTypeUpdateView.as_view(), name="tasktype-update"),
    path('tasktype/<int:pk>/delete/', views.TaskTypeDeleteView.as_view(), name="tasktype-delete"),

    path('taskleader/<int:project_id>/create/', views.TaskLeaderCreateView.as_view(), name="taskleader-create"),
    path('taskleader/<int:pk>/update/', views.TaskLeaderUpdateView.as_view(), name="update-taskleader"),
    path('taskleader/<int:pk>/delete/', views.TaskLeaderDeleteView.as_view(), name="delete-taskleader"),

    path('taskmember/<int:project_id>/create/', views.TaskMemberCreateView.as_view(), name="taskmember-create"),
    path('taskmember/<int:pk>/update/', views.TaskMemberUpdateView.as_view(), name="taskmember-update"),
    path('taskmember/<int:pk>/delete/', views.TaskMemberDeleteView.as_view(), name="taskmember-delete"),

    path('export-tasks/<int:project_id>/<int:role>/', views.export_task_to_csv, name='export-tasks'),

    path('projecttask/<int:project_id>/<int:discipline>/<int:discipline_category>/<int:role>/<int:company>/create/', views.ProjectTaskCreateView.as_view(), name="projecttask-create"),

    path('projecttask-duplicate/', views.ProjectTaskDuplicateView.as_view(), name="projecttask-createmultiple"),

    path('projecttask/<int:pk>/update/', views.ProjectTaskUpdateView.as_view(), name="projecttask-update"),
    path('projecttask/<int:pk>/delete/', views.ProjectTaskDeleteView.as_view(), name="projecttask-delete"),
    path('tasks/<int:pk>/detail/', views.ProjectTaskDetailView.as_view(), name="task-detail"),

    path('roles/import/', views.import_roles, name='import-roles'),

    path('tasktype/import/', views.import_tasktypes, name='import-tasktypes'),

    path('projecttask/import/', views.import_tasks, name='import-projecttask'),

    path('projecttask/import/<int:project_id>/<int:role>/', views.import_project_task, name='import-projecttask-project'),

    path('get-company/', views.get_company, name='get-company'),
    path('get-disciplinecategory/', views.get_disciplinecategory, name='get-disciplinecategory'),

    path('mark-complete/<int:project_id>/<int:role_id>/<int:company_id>/', views.CompleteTaskPage.as_view(), name='mark-complete'),


    path('generate-tidp/<int:project_id>/<int:projectrole_id>/', views.GenerateTidpMidp.as_view(), name='generate-tidp'),
    path('generate-midp/<int:project_id>/', views.GenerateTidpMidp.as_view(), name='generate-midp'),

    path('view-tidp/<int:project_id>/<int:projectrole_id>/', views.ViewTidpMidp.as_view(), name='view-tidp'),
    path('view-midp/<int:project_id>/', views.ViewTidpMidp.as_view(), name='view-midp'),


    path('download-template/<content_type>/', views.download_exl_template, name='download-template'),

    path('project-scales', views.ProjectScaleView.as_view(), name='project-scales'),

    path('project-scales/<int:pk>/update/', views.ProjectScaleUpdateView.as_view(), name='project-scales-update'),

    path('project-scales/<int:pk>/delete/', views.ProjectScaleDeleteView.as_view(), name='project-scales-delete'),
]

tidp/views.py
import copy
from openpyxl import Workbook, load_workbook
from tempfile import NamedTemporaryFile
from django.db.models import F, Count
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import View, ListView, DetailView, TemplateView, FormView
from django.views.generic.edit import UpdateView, DeleteView, CreateView, FormView
from django.contrib.auth.hashers import make_password
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.conf import settings
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView, BSModalFormView

from users.models import User
from design_health.views import AjaxableResponseMixin

from .models import Discipline, Role, Project, ProjectRole, ProjectTask, Task, TaskType, TaskLeader, Company, TaskMember, DisciplineCategory, ProjectScale

from . import forms


def is_super_user(user):
    return user.is_superuser

def is_task_leader(user):
    return user.role == 'task_leader'

def is_team_member(user):
    return user.role == 'team_member'

class SuperuserOnlyMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


@login_required
@user_passes_test(is_super_user)
def role_list_view(request):
    if request.method == 'POST':
        form = forms.RoleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(request.path)

    form = forms.RoleForm()
    role_list = Role.objects.all()
    paginator = Paginator(role_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "form": form,
        "page_obj": page_obj,
    }

    return render(request, 'tidp/roles.html', context)


class RoleUpdateView(LoginRequiredMixin, UserPassesTestMixin, BSModalUpdateView):
    model = Role
    form_class = forms.RoleFormPopup
    success_message = 'Role successfully updated.'
    success_url = reverse_lazy('tidp:roles')
    template_name = 'tidp/popup_update_form.html'

    def test_func(self):
      return self.request.user.is_superuser



class RoleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Role
    template_name = "tidp/delete_form.html"
    success_url = reverse_lazy('tidp:roles')
    success_message = 'Role succesfully deleted.'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Role Delete"
        return context

    def test_func(self):
      return self.request.user.is_superuser

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super().delete(request, *args, **kwargs)


class CompanyListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Company
    template_name = "tidp/company_list.html"
    paginate_by = 10

    def test_func(self):
        return self.request.user.is_superuser


class CompanyCreateView(LoginRequiredMixin, BSModalCreateView):
    model = Company
    form_class = forms.CompanyForm
    template_name = 'tidp/popup_create_form.html'
    success_message = 'New company added'
    success_url = reverse_lazy('tidp:company-list')

    def get_success_url(self):
        if self.request.POST.get('next'):
            return self.request.POST.get('next')
        return self.success_url


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add new company'
        return context



class CompanyUpdateView(LoginRequiredMixin, BSModalUpdateView):
    model = Company
    form_class = forms.CompanyForm
    template_name = 'tidp/popup_update_form.html'
    success_message = 'Company updated successfully'
    success_url = reverse_lazy('tidp:company-list')

    def get_success_url(self):
        if self.request.POST.get('next'):
            return self.request.POST.get('next')
        return self.success_url


class CompanyDeleteView(LoginRequiredMixin, UserPassesTestMixin, BSModalDeleteView):
    model = Company
    template_name = 'tidp/delete_form.html'
    success_url = reverse_lazy('tidp:company-list')
    success_message = 'Company Deleted'

    def test_func(self):
        return self.request.user.is_superuser


class ManageProjects(LoginRequiredMixin, ListView):
    """ Manage all projects """
    model = Project
    template_name = 'tidp/project/project_list.html'

    def get_queryset(self):
        queryset = Project.objects.none()
        params = { x:y for x,y in self.request.GET.items() if y}
        if params:
            queryset = super().get_queryset().filter(**params)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        params = { x:y for x,y in self.request.GET.items() if y}
        context['searchform'] = forms.SearchProject(initial=params)
        return context


class ProjectCreateView(LoginRequiredMixin, BSModalCreateView):
    model = Project
    form_class = forms.ProjectForm
    success_message = 'New project added'
    template_name = "tidp/project/project_form.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)


class ProjectDetailView(SuperuserOnlyMixin, View):
    """ Manage a single project """
    template_name = 'tidp/project/project_detail.html'

    def get(self, request, *args, **kwargs):
        project = Project.objects.get(pk=kwargs['pk'])
        task_leaders = project.taskleader_set.all()
        task_members = project.taskmember_set.all()
        roles = project.projectrole_set.all()
        """ tasks = ProjectTask.objects.filter(project=project).order_by('role', 'company')
        grouped = {}
        for obj in tasks:
            grouped.setdefault((obj.role, obj.company), []).append(obj)

        items = []
        for key, group in grouped.items():
            items.append((key[0], key[1], any([s.is_active for s in group]), group)) """


        """roles = []
        for task in projecttasks.values('role').distinct():
            roles.append(
                (
                    task['role'],
                    Role.objects.values_list('name', flat=True).get(pk=task['role']),
                    projecttasks.filter(role=task['role']),
                )
            ) """

        context = {
            "project": project,
            "roles": roles,
            "task_leaders": task_leaders,
            "task_members": task_members,

        }
        return render(request, self.template_name, context)


class ProjectDetailLeaderView(LoginRequiredMixin, View):
    """ Manage a single project for project leader """
    template_name = 'tidp/project/project_detail_leader.html'

    def get(self, request, *args, **kwargs):
        project = Project.objects.get(pk=kwargs['pk'])
        task_members = project.taskmember_set.all()
        taskleader = TaskLeader.objects.get(project=project, user=request.user)
        roles = project.projectrole_set.filter(role__in=taskleader.roles.all())

        context = {
            "project": project,
            "roles": roles,
            "task_members": task_members,
        }
        return render(request, self.template_name, context)


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, BSModalUpdateView):
    model = Project
    form_class = forms.ProjectForm
    template_name = "tidp/popup_update_form.html"
    success_message = 'Project successfully updated.'

    def test_func(self):
        return self.request.user.is_superuser


class ProjectDeleteView(LoginRequiredMixin, BSModalDeleteView):
    model = Project
    success_url = reverse_lazy('tidp:projects')
    template_name = "tidp/delete_form.html"
    success_message = 'Project deleted.'


class ProjectSubmitToLeadView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        data = request.POST['projectrole']
        projectrole = ProjectRole.objects.filter(pk=data).update(status="pending")
        return JsonResponse({"message": "Success"})


class RoleStatusUpdateView(LoginRequiredMixin, View):
    template_name = 'tidp/popup_update_form.html'
    form_class = forms.RoleStatusForm

    def get(self, request, *args, **kwargs):
        projectrole = ProjectRole.objects.get(pk=kwargs['projectrole_id'])
        form = self.form_class(instance=projectrole)
        context = {
            "form": form,
            "title": "Add new form",
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        projectrole = ProjectRole.objects.get(pk=kwargs['projectrole_id'])
        form = self.form_class(request.POST, instance=projectrole)
        if form.is_valid():
            projectrole.status = form.cleaned_data['status']
            projectrole.comment = form.cleaned_data['comment']
            projectrole.save()
            messages.success(request, 'Project Role successfully updated.')
            return redirect('tidp:project-detail', projectrole.project.id)

        context = {
            "form": form,
            "title": "Add new form",
        }
        return render(request, self.template_name, context)


class DisciplineListView(LoginRequiredMixin, ListView):
    model = Discipline
    template_name = 'tidp/discipline_list.html'
    paginate_by = 20

    def get_queryset(self):
        queryset = super().get_queryset()
        search = self.request.GET.get('name')
        if search:
            queryset = queryset.filter(name__icontains=search)

tidp/templates/tidp/tasks/edit_task.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page-title %}
Edit Task
{% endblock page-title %}
  

{% block content %}

   
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
  
          <div class="form-row">
            {% for field in form %}
                <div class="form-group col-md-6">
                    {{field.label_tag}}
                    {{field|add_class:"form-control"}}
                </div>
            {% endfor %}
          </div>
          <div class="form-group col-12 text-center mt-2">
              <button type="submit" class="btn btn-primary">Update Company</button>
          </div>
  
      </form>
    

{% endblock %}

tidp/templates/tidp/tasks/task_create.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page-title %}
TIDP | Create | {{model}}
{% endblock page-title %}


{% block content %}


<form method="POST">
    {% csrf_token %}

    <div class="form-row">
        {% for field in form %}
          <div class="form-group col-sm-6">
            {{field.label_tag}}
            {{ field|add_class:"form-control"}}
          </div>
        {% endfor %}
      </div>

    <button type="submit" class="mt-4 w-25 btn btn-primary float-right">Create Task</button>
    </div>
  </form>



{% endblock %}

tidp/templates/tidp/tasks/task_detail.html
{% extends "base.html" %}


{% block page-title %}
TIDP | {{task.project.name}} | {{ task}}
{% endblock page-title %}


{% block content %}

<ul class="list-group mt-3">
  <li class="list-group-item">
    <div class="row">
      <div class="col-sm-4">Project Name:</div>
      <div class="col-sm-8">{{ task.project}}</div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="row">
      <div class="col-sm-4">Uniclass Code</div>
      <div class="col-sm-8">{{ task.uniclass_code}}</div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="row">
      <div class="col-sm-4">Discipline:</div>
      <div class="col-sm-8">{{ task.discipline}}</div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="row">
      <div class="col-sm-4">Discipline Category:</div>
      <div class="col-sm-8">{{ task.discipline_category}}</div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="row">
      <div class="col-sm-4">Role:</div>
      <div class="col-sm-8">{{ task.role}}</div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="row">
      <div class="col-sm-4">Task Type:</div>
      <div class="col-sm-8">{{ task.task_type}}</div>
    </div>
  </li>
  <li class="list-group-item">
    <div class="row">
      <div class="col-sm-4">Task Code:</div>
      <div class="col-sm-8">{{ task.unique_code}}</div>
    </div>
  </li>
</ul>

{% endblock %}

tidp/templates/tidp/tasks/task_list.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page-title %}
TIDP | Settings | Tasks
{% endblock page-title %}


{% block content %}
<div>


  <nav>
    <div class="nav nav-tabs" id="nav-tab" role="tablist">
      <a class="nav-item nav-link active" style="border: 1px solid #B11FB3;" id="current-project" data-toggle="tab" href="#current" role="tab" aria-controls="nav-home" aria-selected="true">Existing Tasks</a>
      <a class="nav nav-link bs-modal" data-form-url="{% url 'tidp:task-create' %}" data-toggle="tooltip" style="border: 1px solid #B11FB3;"><i class="fa fa-plus"></i>  Add New Task</a>
      <a href="{% url 'tidp:import-projecttask' %}" class="nav-item nav-link" style="border: 1px solid #B11FB3;" ><i class="fa fa-upload"></i>  Import Tasks </a>

    </div>
  </nav>


  <!-- Main tab -->
  <div class="tab-content" id="nav-tabContent">

    <!-- Tab for search -->
    <div class="tab-pane fade show active" id="current" role="tabpanel" aria-labelledby="current-project">
      <br>

      <form method="GET">
          <div class="form-row">
              {% for field in search %}
                  <div class="col-sm-3">
                      {{field.label_tag}}
                      {{field|add_class:"form-control"}}
                  </div>
              {% endfor %}

              <button type="submit" class="mt-4 btn btn-primary ">Display Tasks</button>


          </div>
      </form>

      <div class="mt-2">
        {% if tasks %}
          <p>List of Tasks</p>

          <table class="table table-bordered table-hover">
              <thead class="thead-light">
              <tr>
                  <th> Description</th>
                  <th> Discipline</th>
                  <th> Discipline Category</th>
                  <th> Task Type</th>
                  <th> Role</th>
                  <th></th>
              </tr>
              </thead>
              <tbody>
              {% for task in tasks %}
                  <tr>
                  <td>{{ task.description}} </td>
                  <td>{{ task.discipline}} </td>
                  <td>{{ task.discipline_category}} </td>
                  <td>{{ task.task_type}} </td>
                  <td>{{ task.role}} </td>
                  <td>
                      <a class="bs-modal" data-form-url="{% url 'tidp:task-update' task.id %}" data-toggle="tooltip"><i class="fa fa-edit"></i></a>
                      <a class="bs-modal" data-form-url="{% url 'tidp:task-delete' task.id %}" data-toggle="tooltip"><i class="fas fa-trash-alt text-danger"></i></a>
                  </td>
                  </tr>
              {% endfor %}
              </tbody>
          </table>
          {% include "paginator.html" with page_obj=tasks %}
        {% else %}
          No task found. Please click ‘Add new task above to create a new project.
        {% endif %}
      </div>
    </div>


    <!-- Tab for add new project -->
    <div class="tab-pane fade" id="new" role="tabpanel"
      aria-labelledby="current-project">
      <br><br>

      <form method="POST">
        {% csrf_token %}

        <div class="form-row">
          {% for field in form %}
            <div class="form-group col-sm-6">
              {{field.label_tag}}
              {{ field|add_class:"form-control"}}
            </div>
          {% endfor %}
        </div>

        <button type="submit" class="mt-4 w-25 btn btn-primary float-right">Submit</button>
      </form>
    </div>


  </div>


</div>



<div class="modal fade" role="dialog" id="modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>


{% endblock %}



{% block script %}
  <script type="text/javascript">
    $(document).ready(function() {
        $(".bs-modal").each(function () {
            $(this).modalForm({
                formURL: $(this).data('form-url')
            });
        });

    });
  </script>
{% endblock script %}

tidp/templates/tidp/tasks/tasktype.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page-title %}
TIDP | Settings | Task Types
{% endblock page-title %}


{% block content %}
  <div class="form-group form-row">
      <button type="button" class="btn btn-primary bs-modal" data-form-url="{% url 'tidp:tasktype-create' %}" data-toggle="tooltip">Add Task Type</button>
      <a href="{% url 'tidp:import-tasktypes' %}" class="ml-2 btn btn-primary"><i class="fa fa-upload"></i> Upload task types from excel</a>
  </div>

  {% if tasktypes %}

    <h6>Current Task Types</h6>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th>#</th>
            <th>Title</th>
            <th>Code</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for tasktype in tasktypes %}
            <tr>
              <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
              <td>{{ tasktype.title }}</td>
              <td>{{ tasktype.code }}</td>
              <td>
                <a class="bs-modal" data-form-url="{% url 'tidp:tasktype-update' tasktype.id %}" data-toggle="tooltip"><i class="fas fa-edit"></i></a>
                <a class="bs-modal" data-form-url="{% url 'tidp:tasktype-update' tasktype.id %}" data-toggle="tooltip" ><i class="fas fa-trash-alt text-danger"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    {% include 'paginator.html' %}

  {% else %}

    <p>No roles added yet</p>

  {% endif %}

  <div class="modal fade" role="dialog" id="modal" tabindex="-1">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

{% endblock %}


{% block script %}
  <script type="text/javascript">
    $(document).ready(function() {
        $(".bs-modal").each(function () {
            $(this).modalForm({
                formURL: $(this).data('form-url')
            });
        });

    });
  </script>
{% endblock script %}