autobim/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import signin, signout
from home.views import dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='home'),
    
    path('login/', signin, name='login'),
    path('logout/', signout, name='logout'),

    path('users/', include('users.urls')),
    path('design-check/', include('design_health.urls')),
    path('tidp/', include('tidp.urls')),
]

tidp/urls.py
from django.urls import path

from . import views

app_name = 'tidp'

urlpatterns = [
    path('roles/', views.role_list_view, name='roles'),
    path('roles/<int:pk>/update/', views.RoleUpdateView.as_view(), name="role-update"),
    path('roles/<int:pk>/delete/', views.RoleDeleteView.as_view(), name="role-delete"),

    path('company/list/', views.CompanyListView.as_view(),
       name='company-list'),
    path('company/create/', views.CompanyCreateView.as_view(),
        name='create-company'),
    path('company/<int:pk>/update/', views.CompanyUpdateView.as_view(), name="company-update"),
    path('company/<int:pk>/delete/', views.CompanyDeleteView.as_view(), name="company-delete"),

    path('projects/', views.ManageProjects.as_view(), name='projects'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/manage/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('project/<int:pk>/lmanage/', views.ProjectDetailLeaderView.as_view(), name='project-detail-leader'),
    path('projects/<int:pk>/update/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('projects/submit-to-lead/', views.ProjectSubmitToLeadView.as_view(), name='project-submit-to-lead'),
    path('projects/role-status-update/<int:projectrole_id>/', views.RoleStatusUpdateView.as_view(), name='role-status-update'),

    path('project-discipline/', views.DisciplineListView.as_view(), name='project-discipline'),
    path('project-discipline/create/', views.DisciplineCreateView.as_view(), name='discipline-create'),
    path('discipline/<int:pk>/update/', views.DisciplineUpdateView.as_view(), name='update-discipline'),
    path('discipline/<int:pk>/delete/', views.DisciplineDeleteView.as_view(), name='delete-discipline'),

    path('discipline-categories/', views.DisciplineCategoryListView.as_view(), name='project-discipline-categories'),
    path('discipline-categories/create/', views.DisciplineCategoryCreateView.as_view(), name='discipline-category-create'),
    path('discipline-categories/<int:pk>/update/', views.DisciplineCategoryUpdateView.as_view(), name='update-discipline-category'),
    path('discipline-categories/<int:pk>/delete/', views.DisciplineCategoryDeleteView.as_view(), name='delete-discipline-category'),

    path('tasks/', views.TaskListView.as_view(), name='tasks'),
    path('tasks/create/', views.TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:pk>/update/', views.TaskUpdateView.as_view(), name="task-update"),
    path('tasks/<int:pk>/delete/', views.TaskDeleteView.as_view(), name="task-delete"),

    path('tasktype/', views.TaskTypeView.as_view(), name='tasktypes'),
    path('tasktype/create/', views.TaskTypeCreateView.as_view(), name='tasktype-create'),
    path('tasktype/<int:pk>/update/', views.TaskTypeUpdateView.as_view(), name="tasktype-update"),
    path('tasktype/<int:pk>/delete/', views.TaskTypeDeleteView.as_view(), name="tasktype-delete"),

    path('taskleader/<int:project_id>/create/', views.TaskLeaderCreateView.as_view(), name="taskleader-create"),
    path('taskleader/<int:pk>/update/', views.TaskLeaderUpdateView.as_view(), name="update-taskleader"),
    path('taskleader/<int:pk>/delete/', views.TaskLeaderDeleteView.as_view(), name="delete-taskleader"),

    path('taskmember/<int:project_id>/create/', views.TaskMemberCreateView.as_view(), name="taskmember-create"),
    path('taskmember/<int:pk>/update/', views.TaskMemberUpdateView.as_view(), name="taskmember-update"),
    path('taskmember/<int:pk>/delete/', views.TaskMemberDeleteView.as_view(), name="taskmember-delete"),

    path('export-tasks/<int:project_id>/<int:role>/', views.export_task_to_csv, name='export-tasks'),

    path('projecttask/<int:project_id>/<int:discipline>/<int:discipline_category>/<int:role>/<int:company>/create/', views.ProjectTaskCreateView.as_view(), name="projecttask-create"),

    path('projecttask-duplicate/', views.ProjectTaskDuplicateView.as_view(), name="projecttask-createmultiple"),

    path('projecttask/<int:pk>/update/', views.ProjectTaskUpdateView.as_view(), name="projecttask-update"),
    path('projecttask/<int:pk>/delete/', views.ProjectTaskDeleteView.as_view(), name="projecttask-delete"),
    path('tasks/<int:pk>/detail/', views.ProjectTaskDetailView.as_view(), name="task-detail"),

    path('roles/import/', views.import_roles, name='import-roles'),

    path('tasktype/import/', views.import_tasktypes, name='import-tasktypes'),

    path('projecttask/import/', views.import_tasks, name='import-projecttask'),

    path('projecttask/import/<int:project_id>/<int:role>/', views.import_project_task, name='import-projecttask-project'),

    path('get-company/', views.get_company, name='get-company'),
    path('get-disciplinecategory/', views.get_disciplinecategory, name='get-disciplinecategory'),

    path('mark-complete/<int:project_id>/<int:role_id>/<int:company_id>/', views.CompleteTaskPage.as_view(), name='mark-complete'),


    path('generate-tidp/<int:project_id>/<int:projectrole_id>/', views.GenerateTidpMidp.as_view(), name='generate-tidp'),
    path('generate-midp/<int:project_id>/', views.GenerateTidpMidp.as_view(), name='generate-midp'),

    path('view-tidp/<int:project_id>/<int:projectrole_id>/', views.ViewTidpMidp.as_view(), name='view-tidp'),
    path('view-midp/<int:project_id>/', views.ViewTidpMidp.as_view(), name='view-midp'),


    path('download-template/<content_type>/', views.download_exl_template, name='download-template'),

    path('project-scales', views.ProjectScaleView.as_view(), name='project-scales'),

    path('project-scales/<int:pk>/update/', views.ProjectScaleUpdateView.as_view(), name='project-scales-update'),

    path('project-scales/<int:pk>/delete/', views.ProjectScaleDeleteView.as_view(), name='project-scales-delete'),
]

tidp/forms.py
from django import forms
from django.forms import modelformset_factory, BaseModelFormSet
from django.core.validators import FileExtensionValidator
from bootstrap_modal_forms.forms import BSModalModelForm

from .models import Role, Discipline, Task, Project, TaskLeader, Company, TaskMember, TaskType, DisciplineCategory, ProjectTask, ProjectRole, ProjectScale


class DisciplineForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = Discipline
        fields = ['name']


class DisciplineCategoryForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = DisciplineCategory
        exclude = ()


class DisciplineSearchForm(forms.Form):
    name = forms.CharField(required=False)


class CompanyForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = Company
        fields = '__all__'


class RoleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Role
        fields = ['name', 'code']


class RoleFormPopup(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = Role
        fields = ['name', 'code']


class TaskForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = Task
        exclude = ('is_active',)


class TaskTypeForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = TaskType
        exclude = ()


class TaskSearchForm(forms.Form):
    discipline = forms.ModelChoiceField(Discipline.objects.all(), required=False, widget=forms.Select(attrs={"class":"searchable"}))
    discipline_category = forms.ModelChoiceField(DisciplineCategory.objects.all(), required=False, widget=forms.Select(attrs={"class":"searchable"}))
    role = forms.ModelChoiceField(Role.objects.all(), required=False, widget=forms.Select(attrs={"class":"searchable"}))


class SearchProject(forms.Form):
    name__icontains = forms.CharField(
        max_length=200,
        label="Search for a project",
        required=False,
    )
    client = forms.ModelChoiceField(
        queryset=Company.objects.all(),
        required=False,
        widget=forms.Select(attrs={"class":"searchable"}),
        label='Company'
    )


class ProjectForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'client':
                field.widget.attrs['class'] = 'form-control form-control-sm'
            else:
                field.widget.attrs['class'] = 'form-control searchable'

    class Meta:
        model = Project
        exclude = ('author',)


class ProjectTaskForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = ProjectTask
        fields = ('description', 'uniclass_code', 'task_type')


class TaskLeaderForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name in ['company', 'roles'] :
                field.widget.attrs['class'] = 'searchable form-control form-control-sm'
            else:
                field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = TaskLeader
        exclude = ('project', 'user')



class TaskMemberForm(BSModalModelForm):
    def __init__(self, roles=None, *args, **kwargs):
        project = kwargs.pop('project')
        super(TaskMemberForm, self).__init__(*args, **kwargs)
        leader = TaskLeader.objects.filter(user=self.request.user, project=project).first()
        if leader:
            self.fields['roles'].queryset = leader.roles.all()
        for field_name, field in self.fields.items():
            if field_name in ['company', 'roles'] :
                field.widget.attrs['class'] = 'searchable'
            else:
                field.widget.attrs['class'] = 'form-control form-control-sm'

    class Meta:
        model = TaskMember
        exclude = ('project','company', 'user')


class Importer(forms.Form):
    header = forms.BooleanField(
        required=False,
        initial=True,
        widget=forms.CheckboxInput(attrs={"class":"form-check-input"}),
    )
    excel_file = forms.FileField(
        widget=forms.FileInput(
            attrs={
                'accept':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel',
                'class': 'custom-file-input',
            }
        ),
        validators=[FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])],
    )


class ImportTaskForm(forms.Form):
    discipline = forms.ModelChoiceField(Discipline.objects.all(), required=False, widget=forms.Select(attrs={"class":"searchable form-control"}))
    discipline_category = forms.ModelChoiceField(DisciplineCategory.objects.all(), required=False, widget=forms.Select(attrs={"class":"searchable form-control"}))
    header = forms.BooleanField(
        required=False,
        initial=True,
        widget=forms.CheckboxInput(attrs={"class":"form-check-input"}),
    )
    excel_file = forms.FileField(
        widget=forms.FileInput(
            attrs={
                'accept':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel',
                'class': 'custom-file-input',
            }
        ),
        validators=[FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])],
    )


class ImportProjectTaskForm(forms.Form):
    header = forms.BooleanField(
        required=False,
        initial=True,
        widget=forms.CheckboxInput(attrs={"class":"form-check-input"}),
    )
    excel_file = forms.FileField(
        widget=forms.FileInput(
            attrs={
                'accept':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel',
                'class': 'custom-file-input',
            }
        ),
        validators=[FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])],
    )


class StandardTemplateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True

    CHOICES = [
        ('Models', 'MODELS'),
        ('Drawings', 'DRAWINGS'),
        ('Reports', 'REPORTS'),
        ('Specifications', 'SPECIFICATIONS'),
        ('Others', 'OTHERS'),
    ]

    task_category = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = ProjectTask
        fields = ('volume', 'level', 'exchange_formats', 'task_category')


class ScottishTemplateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True

    CHOICES = [
        ('Project information', 'Project information'),
        ('Site, ground and environmental information', 'Site, ground and environmental information'),
        ('Project performance requirements', 'Project performance requirements'),
        ('Design and approvals information', 'Design and approvals information'),
        ('Financial and commercial information', 'Financial and commercial information'),
        ('Contract information', 'Contract information'),
        ('Construction management information', 'Construction management information'),
        ('Testing, Commissioning and completion information', 'Testing, Commissioning and completion information'),
        ('Asset management information', 'Asset management information'),
    ]

    task_category = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = ProjectTask
        fields = ('uniclass_code', 'scale_or_size', 'eir_reference', 'pir_reference', 'air_reference', 'task_category')


class BalfourBeattyTemplateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.required = True

    class Meta:
        model = ProjectTask
        fields = ('volume', 'location', 'estimated_production_duration', 'uniclass_code')


CompleteTasks = modelformset_factory(ProjectTask, fields=(), extra=0)



class ProjectTaskCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'clone':
                field.widget.attrs['class'] = 'form-control'

tidp/templates/tidp/company_list.html
{% extends "base.html" %}
{% load widget_tweaks %}



{% block page-title %}
  TIDP | Manage Companies
{% endblock page-title %}


{% block content %}

    <button type="button" class="btn btn-primary non-submit-btn mb-3 bs-modal" data-form-url="{% url 'tidp:create-company' %}" data-toggle="tooltip"><i class="fa fa-plus"></i> Add new company</button>

    {% if object_list %}
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead class="thead-light text-center">
          <tr>
            <th>Company Name</th>
            <th>Address</th>
            <th>Telephone</th>
            <th>Email</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td>{{object}}</td>
            <td>{{object.full_address}}</td>
            <td>{{object.phone_number}}</td>
            <td>{{object.email}}</td>
            <td>
              <a class="bs-modal" data-form-url="{% url 'tidp:company-update' object.id %}" data-toggle="tooltip"><i
                  class="fas fa-edit"></i></a>
              <a class="bs-modal" data-form-url="{% url 'tidp:company-delete' object.id %}" data-toggle="tooltip"><i
                  class="fas fa-trash text-danger"></i></a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
      {% include 'paginator.html' %}
    {% else %}

      <p>There are no company yet.</p>
    {% endif %}


    <div class="modal fade" role="dialog" id="modal" tabindex="-1">
      <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
      </div>
    </div>

{% endblock %}


{% block script %}
  <script type="text/javascript">
    $(document).ready(function() {
        $(".bs-modal").each(function () {
            $(this).modalForm({
                formURL: $(this).data('form-url')
            });
        });

    });
  </script>
{% endblock script %}

tidp/templates/tidp/delete_form.html
<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h5 class="modal-title">Delete {{object}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p>Are you sure you want to delete <strong>{{ object }}</strong>?</p>
    <div class="mt-2 red-text">This action cannot be undone</div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger"> <i class="fas fa-trash-alt"></i>Delete</button>
  </div>

</form>

tidp/templates/tidp/discipline_category.html
{% extends "base.html" %}
{% load widget_tweaks %}



{% block page-title %}
  TIDP | Settings | Discipline Categories
{% endblock page-title %}


{% block content %}

  <button class="btn btn-primary bs-modal mb-3" data-form-url="{% url 'tidp:discipline-category-create' %}" data-toggle="tooltip"><i class="fa fa-plus"></i> Add new discipline category</button>

  <form method="GET">
      <div class="row">
          {% for field in search %}
              <div class="form-group col-12 col-md-6 ">
                  {{ field|add_class:"form-control"}}
              </div>
          {% endfor %}

          <div>
              <button type="submit" class="btn btn-primary">Search</button>
          </div>
      </div>


  </form>

  {% if disciplines %}
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th>Discipline</th>
          <th>Category</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for object in disciplines %}
        <tr>
          <td>{{object.discipline}}</td>
          <td>{{object.category}}</td>
          <td>
            <a class="bs-modal" data-form-url="{% url 'tidp:update-discipline-category' object.id %}" data-toggle="tooltip"><i
                class="fas fa-edit"></i></a>
            <a class="bs-modal" data-form-url="{% url 'tidp:delete-discipline-category' object.id %}" data-toggle="tooltip"><i
                class="fas fa-trash text-danger"></i></a>
          </td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
    {% include 'paginator.html' with page_obj=disciplines %}
  {% else %}

    <p>There are no discipline yet.</p>
  {% endif %}

  <div class="modal fade" role="dialog" id="modal" tabindex="-1">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

{% endblock %}


{% block script %}
  <script type="text/javascript">
    $(document).ready(function() {
        $(".bs-modal").each(function () {
            $(this).modalForm({
                formURL: $(this).data('form-url')
            });
        });

    });
  </script>
{% endblock script %}

tidp/templates/tidp/discipline_list.html
{% extends "base.html" %}
{% load widget_tweaks %}



{% block page-title %}
  TIDP | Settings | Project Discipline
{% endblock page-title %}


{% block content %}

    <button class="btn btn-primary bs-modal mb-3" data-form-url="{% url 'tidp:discipline-create' %}" data-toggle="tooltip"><i class="fa fa-plus"></i> Add new discipline</button>


    <form method="GET">
        <div class="row">
            {% for field in search %}
                <div class="form-group col-12 col-md-6 ">
                    {{ field|add_class:"form-control"}}
                </div>
            {% endfor %}

            <div>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>


    </form>

    {% if object_list %}
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th>Type Description</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for object in object_list %}
          <tr>
            <td>{{object}}</td>
            <td>
              <a class="bs-modal" data-form-url="{% url 'tidp:update-discipline' object.id %}" data-toggle="tooltip"><i
                  class="fas fa-edit"></i></a>
              <a class="bs-modal" data-form-url="{% url 'tidp:delete-discipline' object.id %}" data-toggle="tooltip"><i
                  class="fas fa-trash text-danger"></i></a>
            </td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
      {% include 'paginator.html' %}
    {% else %}

      <p>There are no discipline yet.</p>
    {% endif %}


    <div class="modal fade" role="dialog" id="modal" tabindex="-1">
      <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
      </div>
    </div>

{% endblock %}

tidp/templates/tidp/importer.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block page-title %}
Import {{object}} from excel
{% endblock page-title %}


{% block content %}

<p>{{instruction | safe}} </p>

    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}

                <div class="form-check mb-3">
                    {{form.header}}
                    <label class="form-check-label" for="id_header">First row is header</label>
                </div>

                <div class="input-group mb-3">
                    <div class="custom-file">
                      {{form.excel_file}}
                      <label class="custom-file-label" for="id_excel_file">Choose file</label>
                    </div>
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit">Upload</button>
                    </div>
                </div>

            </form>
        </div>
    </div>




{% endblock %}

tidp/templates/tidp/multiple_task_create.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}


{% block page-title %}
TIDP | Create | Project Task
{% endblock page-title %}


{% block content %}


<form method="POST">
    {% csrf_token %}
    {{ formset.management_form }}

    <table class="table table-sm">
        <thead>
            <tr>
                <th></th>
                <th>Task Title:</th>
                <th>Uniclass code:</th>
                <th>Task type/form of information:</th>
            </tr>
        </thead>
        <tbody>

            {% for form in formset %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    {% for field in form.visible_fields %}
                        <td>{{ field|add_class:"form-control form-control-sm"}}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <button type="submit" class="mt-4 w-25 btn btn-primary float-right">Create Tasks</button>

</form>



{% endblock %}

tidp/templates/tidp/popup_create_form.html
{% load static %}

<form method="POST">
    {% csrf_token %}

    <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">{{title}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>

    <div class="modal-body invalid">
        <div>{{ form.non_field_errors }}</div>
        <div class="form-row">

            {% for hidden in form.hidden_fields %}
                {{hidden}}
            {% endfor %}

            {% for field in form.visible_fields %}
                <div class="form-group col-sm-6">
                    {{field.label_tag}}
                    {{field}}

                    <small class="form-text text-muted">
                    {% for error in field.errors %}
                        {{error}}
                    {% endfor %}
                    </small>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="modal-footer">
        <input type="hidden" name="next" id="next" value="{{request.GET.next}}">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="submit-btn btn btn-primary">Create</button>
      </div>
</form>

<script src="{% static 'dist/js/custom.js' %}"></script>

tidp/templates/tidp/popup_update_form.html
{% load static %}

<form method="POST">
    {% csrf_token %}
    <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Update {{object}}</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>

    <div class="modal-body">
        <div class="form-row invalid">
            {% for field in form %}
                <div class="form-group col-sm-6">
                    {{field.label_tag}}
                    {{field}}

                    <small class="form-text text-muted">
                    {% for error in field.errors %}
                        {{error}}
                    {% endfor %}
                    </small>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="submit-btn btn btn-primary">Update</button>
      </div>
</form>

<script src="{% static 'dist/js/custom.js' %}"></script>

tidp/templates/tidp/roles.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page-title %}
Role/Responsibility
{% endblock page-title %}


{% block content %}

  <form method="POST">
      {% csrf_token %}
      <div class="form-group form-row">
          <div class="col-sm-3">
            {{form.name|add_class:"form-control"|attr:"placeholder:Role Name"}}
          </div>
          <div class="col-sm-3">
            {{form.code|add_class:"form-control"|attr:"placeholder:Role Code"}}
          </div>
          <button type="submit" class="btn btn-primary">Add Role</button>
          <a href="{% url 'tidp:import-roles' %}" class="ml-2 btn btn-primary"><i class="fa fa-upload"></i> Upload from excel</a>
      </div>
  </form>

  {% if page_obj %}

    <h6>Current Roles</h6>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th>#</th>
            <th>Role</th>
            <th>Code</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for role in page_obj %}
            <tr>
              <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
              <td>{{ role.name }}</td>
              <td>{{ role.code }}</td>
              <td>
                <a class="bs-modal" data-form-url="{% url 'tidp:role-update' role.id %}" data-toggle="tooltip"><i class="fas fa-edit"></i></a>
                <a class="bs-modal" data-form-url="{% url 'tidp:role-delete' role.id %}" data-toggle="tooltip"><i class="fas fa-trash-alt text-danger"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    {% include 'paginator.html' %}

  {% else %}

    <p>No roles added yet</p>

  {% endif %}


  <div class="modal fade" role="dialog" id="modal" tabindex="-1">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

{% endblock %}