autobim/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import signin, signout
from home.views import dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='home'),
    
    path('login/', signin, name='login'),
    path('logout/', signout, name='logout'),

    path('users/', include('users.urls')),
    path('design-check/', include('design_health.urls')),
    path('tidp/', include('tidp.urls')),
]

tidp/urls.py
from django.urls import path

from . import views

app_name = 'tidp'

urlpatterns = [
    path('roles/', views.role_list_view, name='roles'),
    path('roles/<int:pk>/update/', views.RoleUpdateView.as_view(), name="role-update"),
    path('roles/<int:pk>/delete/', views.RoleDeleteView.as_view(), name="role-delete"),

    path('company/list/', views.CompanyListView.as_view(),
       name='company-list'),
    path('company/create/', views.CompanyCreateView.as_view(),
        name='create-company'),
    path('company/<int:pk>/update/', views.CompanyUpdateView.as_view(), name="company-update"),
    path('company/<int:pk>/delete/', views.CompanyDeleteView.as_view(), name="company-delete"),

    path('projects/', views.ManageProjects.as_view(), name='projects'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/manage/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('project/<int:pk>/lmanage/', views.ProjectDetailLeaderView.as_view(), name='project-detail-leader'),
    path('projects/<int:pk>/update/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('projects/submit-to-lead/', views.ProjectSubmitToLeadView.as_view(), name='project-submit-to-lead'),
    path('projects/role-status-update/<int:projectrole_id>/', views.RoleStatusUpdateView.as_view(), name='role-status-update'),

    path('project-discipline/', views.DisciplineListView.as_view(), name='project-discipline'),
    path('project-discipline/create/', views.DisciplineCreateView.as_view(), name='discipline-create'),
    path('discipline/<int:pk>/update/', views.DisciplineUpdateView.as_view(), name='update-discipline'),
    path('discipline/<int:pk>/delete/', views.DisciplineDeleteView.as_view(), name='delete-discipline'),

    path('discipline-categories/', views.DisciplineCategoryListView.as_view(), name='project-discipline-categories'),
    path('discipline-categories/create/', views.DisciplineCategoryCreateView.as_view(), name='discipline-category-create'),
    path('discipline-categories/<int:pk>/update/', views.DisciplineCategoryUpdateView.as_view(), name='update-discipline-category'),
    path('discipline-categories/<int:pk>/delete/', views.DisciplineCategoryDeleteView.as_view(), name='delete-discipline-category'),

    path('tasks/', views.TaskListView.as_view(), name='tasks'),
    path('tasks/create/', views.TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:pk>/update/', views.TaskUpdateView.as_view(), name="task-update"),
    path('tasks/<int:pk>/delete/', views.TaskDeleteView.as_view(), name="task-delete"),

    path('tasktype/', views.TaskTypeView.as_view(), name='tasktypes'),
    path('tasktype/create/', views.TaskTypeCreateView.as_view(), name='tasktype-create'),
    path('tasktype/<int:pk>/update/', views.TaskTypeUpdateView.as_view(), name="tasktype-update"),
    path('tasktype/<int:pk>/delete/', views.TaskTypeDeleteView.as_view(), name="tasktype-delete"),

    path('taskleader/<int:project_id>/create/', views.TaskLeaderCreateView.as_view(), name="taskleader-create"),
    path('taskleader/<int:pk>/update/', views.TaskLeaderUpdateView.as_view(), name="update-taskleader"),
    path('taskleader/<int:pk>/delete/', views.TaskLeaderDeleteView.as_view(), name="delete-taskleader"),

    path('taskmember/<int:project_id>/create/', views.TaskMemberCreateView.as_view(), name="taskmember-create"),
    path('taskmember/<int:pk>/update/', views.TaskMemberUpdateView.as_view(), name="taskmember-update"),
    path('taskmember/<int:pk>/delete/', views.TaskMemberDeleteView.as_view(), name="taskmember-delete"),

    path('export-tasks/<int:project_id>/<int:role>/', views.export_task_to_csv, name='export-tasks'),

    path('projecttask/<int:project_id>/<int:discipline>/<int:discipline_category>/<int:role>/<int:company>/create/', views.ProjectTaskCreateView.as_view(), name="projecttask-create"),

    path('projecttask-duplicate/', views.ProjectTaskDuplicateView.as_view(), name="projecttask-createmultiple"),

    path('projecttask/<int:pk>/update/', views.ProjectTaskUpdateView.as_view(), name="projecttask-update"),
    path('projecttask/<int:pk>/delete/', views.ProjectTaskDeleteView.as_view(), name="projecttask-delete"),
    path('tasks/<int:pk>/detail/', views.ProjectTaskDetailView.as_view(), name="task-detail"),

    path('roles/import/', views.import_roles, name='import-roles'),

    path('tasktype/import/', views.import_tasktypes, name='import-tasktypes'),

    path('projecttask/import/', views.import_tasks, name='import-projecttask'),

    path('projecttask/import/<int:project_id>/<int:role>/', views.import_project_task, name='import-projecttask-project'),

    path('get-company/', views.get_company, name='get-company'),
    path('get-disciplinecategory/', views.get_disciplinecategory, name='get-disciplinecategory'),

    path('mark-complete/<int:project_id>/<int:role_id>/<int:company_id>/', views.CompleteTaskPage.as_view(), name='mark-complete'),


    path('generate-tidp/<int:project_id>/<int:projectrole_id>/', views.GenerateTidpMidp.as_view(), name='generate-tidp'),
    path('generate-midp/<int:project_id>/', views.GenerateTidpMidp.as_view(), name='generate-midp'),

    path('view-tidp/<int:project_id>/<int:projectrole_id>/', views.ViewTidpMidp.as_view(), name='view-tidp'),
    path('view-midp/<int:project_id>/', views.ViewTidpMidp.as_view(), name='view-midp'),


    path('download-template/<content_type>/', views.download_exl_template, name='download-template'),

    path('project-scales', views.ProjectScaleView.as_view(), name='project-scales'),

    path('project-scales/<int:pk>/update/', views.ProjectScaleUpdateView.as_view(), name='project-scales-update'),

    path('project-scales/<int:pk>/delete/', views.ProjectScaleDeleteView.as_view(), name='project-scales-delete'),
]

tidp/models.py
import re
from django.db import models
from django.db.models import Count
from django.urls import reverse
from django.conf import settings

from .utils import TASK_CHOICES, CATEGORY_CHOICES


class Company(models.Model):
    company_name = models.CharField(max_length=80, unique=True)
    street_number = models.CharField(max_length=5, blank=True)
    street_name = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=50, blank=True)
    postal_code = models.CharField(max_length=10, blank=True)
    phone_number = models.CharField(max_length=15, blank=True)
    contact_person = models.CharField(max_length=30, blank=True)
    email = models.EmailField()
    originator_code = models.CharField(max_length=6, default="ZZ")

    def __str__(self):
        return self.company_name

    @property
    def full_address(self):
        return f'{self.street_number}, {self.street_name}, {self.city}, {self.postal_code}, {self.country}'

class Discipline(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return f'{self.name}'


class DisciplineCategory(models.Model):
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    category = models.CharField(max_length=200)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['discipline', 'category'], name='unique_category')
        ]

    def __str__(self):
        return f'{self.discipline} - {self.category}'


class Role(models.Model):
  STATUS = [
    ('active', 'Active'),
    ('inactive', 'Inactive'),
  ]
  name = models.CharField(max_length=80, unique=True)
  code = models.CharField(max_length=200, blank=True)
  status = models.CharField(max_length=31, choices=STATUS, default="active")
  date_added = models.DateTimeField(auto_now_add=True)

  def __str__(self):
      return f'{self.name}'


class TaskType(models.Model):
    title = models.CharField(max_length=200, unique=True)
    code = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Task(models.Model):
    description = models.CharField(verbose_name="Task Title", max_length=100)
    uniclass_code = models.CharField(max_length=20, blank=True)
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    discipline_category = models.ForeignKey(DisciplineCategory, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True)
    task_type = models.ForeignKey(TaskType, on_delete=models.SET_NULL, null=True, verbose_name='Task type/form of information')

    def __str__(self):
        return self.description

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['description', 'discipline', 'discipline_category', 'role', 'task_type'], name='unique_task')
        ]


class ProjectScale(models.Model):
    scale = models.IntegerField()

    def __str__(self):
        return f'{self.scale}'



class Project(models.Model):
    TEMPLATES = [
        ('standard_template', 'Standard Template'),
        ('scottish_template', 'Scottish Template'),
        ('balfour_beatty_template', 'Balfour Beatty Template'),
    ]
    name = models.CharField(max_length=100)
    client = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, related_name="tipd_project_client")
    number = models.CharField(max_length=10, blank=True)
    code = models.CharField(max_length=6)
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    discipline_category = models.ForeignKey(DisciplineCategory, on_delete=models.CASCADE)
    midp_tipd_template = models.CharField(verbose_name='MIDP/TIDP Template', max_length=50, choices=TEMPLATES, default='standard_template')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('tidp:project-detail', kwargs={'pk': self.pk})


class TaskLeader(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, verbose_name='Company/Originator', null=True)
    contact_person = models.CharField(max_length=200)
    contact_email = models.EmailField()
    roles = models.ManyToManyField(Role)

    def __str__(self):
        return f'Task leader {self.contact_person}'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'project'], name='unique_leader')
        ]


class TaskMember(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, verbose_name='Company/Originator')
    contact_person = models.CharField(max_length=200)
    contact_email = models.EmailField()
    roles = models.ManyToManyField(Role)

    def __str__(self):
        return f'Task member for {self.project}'

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'project'], name='unique_member')
        ]


class ProjectRole(models.Model):
    STATUSES = [
        ('not_sent', 'Not Sent'),
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    comment = models.TextField(blank=True)
    status = models.CharField(choices=STATUSES, max_length=20, default='not_sent')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.role.name} - {self.company.company_name}'


class ProjectTask(models.Model):
    project_role = models.ForeignKey(ProjectRole, on_delete=models.CASCADE)
    description = models.CharField(verbose_name="Task Title", max_length=100)
    uniclass_code = models.CharField(max_length=20, blank=True)
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    discipline_category = models.ForeignKey(DisciplineCategory, on_delete=models.CASCADE)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE, verbose_name='Task type/form of information')
    volume = models.CharField(max_length=100, blank=True)
    level = models.CharField(max_length=100, blank=True)
    task_category = models.CharField(max_length=100, blank=True)
    exchange_formats = models.CharField(max_length=100, blank=True)
    scale_or_size = models.ForeignKey(ProjectScale, on_delete=models.SET_NULL, null=True, verbose_name='Scale/Size', blank=True)
    eir_reference = models.CharField(verbose_name='EIR Reference', max_length=100, blank=True)
    pir_reference = models.CharField(verbose_name='PIR Reference', max_length=100, blank=True)
    air_reference = models.CharField(verbose_name='AIR Reference', max_length=100, blank=True)
    location = models.CharField(max_length=100, blank=True)
    estimated_production_duration = models.CharField(max_length=100, blank=True)
    code = models.IntegerField(editable=False, default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['task_type']


    def __str__(self):
        return f'{self.description}'

    @property
    def get_role(self):
        mymatch = re.search(r'\((.+)\)', self.project_role.role.name)
        mrole = mymatch.group(1) if mymatch else '-'
        return mrole

    @property
    def get_tasktype(self):
        mymatch = re.search(r'\((.+)\)', self.task_type.title)
        mdiscipline = mymatch.group(1) if mymatch else '-'
        return mdiscipline

    @property
    def unique_code(self):
        if self.project_role.is_active:
            return '-'
        else:
            number = format(self.code, '05d')
            return f'{self.project_role.project.code}-{self.project_role.project.client.originator_code}-{self.volume}-{self.level}-{self.get_tasktype}-{self.get_role}-{number}'

tidp/templates/tidp/project/project_detail.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page-title %}
TIDP | Project | {{project}}
{% endblock page-title %}


{% block content %}

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" style="border: 1px solid #B11FB3;">
    <a class="nav-link active" id="detail-tab" data-toggle="tab" href="#detail" role="tab" aria-controls="detail" aria-selected="true"><i class="fa fa-eye"></i> Project Details</a>
  </li>
  <li class="nav-item" style="border: 1px solid #B11FB3;">
    <a class="nav-link" id="tasks-tab" data-toggle="tab" href="#tasks" role="tab" aria-controls="tasks" aria-selected="false"><i class="fa fa-bars"></i> Tasks</a>
  </li>
  <li class="nav-item" style="border: 1px solid #B11FB3;">
    <a class="nav-link" id="leaders-tab" data-toggle="tab" href="#leaders" role="tab" aria-controls="leaders" aria-selected="false"><i class="fa fa-users"></i> Task Leaders</a>
  </li>
  <li class="nav-item" style="border: 1px solid #B11FB3;">
    <a class="nav-link" id="members-tab" data-toggle="tab" href="#members" role="tab" aria-controls="members" aria-selected="false"><i class="fa fa-users"></i> Task Members</a>
  </li>

</ul>

<div class="tab-content" id="myTabContent">

  <!-- Project Details -->
  <div class="tab-pane fade show active" id="detail" role="tabpanel" aria-labelledby="detail-tab">
      <ul class="list-group mt-3">
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3">Project Name:</div>
            <div class="col-sm-9">{{project.name}} </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3">Client:</div>
            <div class="col-sm-9">{{project.client}} </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3">Project Number:</div>
            <div class="col-sm-9">{{project.number}} </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3">Project Code:</div>
            <div class="col-sm-9">{{project.code}} </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3">Project Discipline:</div>
            <div class="col-sm-9">{{project.discipline}} </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3">Discipline Category:</div>
            <div class="col-sm-9">{{project.discipline_category}} </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-sm-3">MIDP/TIDP Template:</div>
            <div class="col-sm-9">{{project.get_midp_tipd_template_display}} </div>
          </div>
        </li>
        {% if request.user.is_superuser %}
        <li class="list-group-item">
          <a class="btn btn-secondary text-white bs-modal" data-form-url="{% url 'tidp:project-update' project.id %}" data-toggle="tooltip"><i class="fa fa-edit"></i> Edit Project</a>
          <a class="btn btn-danger text-white bs-modal" data-form-url="{% url 'tidp:project-delete' project.id %}" data-toggle="tooltip"><i class="fa fa-trash"></i> Delete Project</a>
        </li>
        {% endif %}

    </ul>

  </div>

  <!-- Tasks -->
  <div class="tab-pane fade" id="tasks" role="tabpanel" aria-labelledby="tasks-tab">
    <div class="mt-3">
      {% if roles %}

        {% for role in roles %}
          <h5>{{role.role.name}} - {{role.company.company_name}}</h5>
          <div class="mb-2">
            <a href="{% url 'tidp:projecttask-create' project.id project.discipline.id project.discipline_category.id role.id role.company.id %}" class="btn btn-sm btn-primary">Add new task <i class="fa fa-plus"></i></a>
            <a href="{% url 'tidp:import-projecttask-project' project.id role.id %}" class="btn btn-sm btn-info">Import Tasks <i class="fa fa-upload"></i> </a>
            <a href="{% url 'tidp:export-tasks' project.id role.id %}" class="btn btn-sm btn-secondary">Export to excel <i class="fa fa-download"></i></a>

            <div class="float-right">
            {% if role.is_active %}
              <a href="{% url 'tidp:mark-complete' project.id role.role.id role.company.id %}" class="btn btn-sm btn-danger">Proceed to complete tasks > </a>

            {% else %}

              <a href="{% url 'tidp:generate-tidp' project.id role.id %}" class="btn btn-success btn-sm">Generate TIDP for {{role.role.name}} <i class="fa fa-download"></i> </a>
              <a href="{% url 'tidp:view-tidp' project.id role.id %}" class="btn btn-info btn-sm">View TIDP <i class="fa fa-eye"></i> </a>
              <button type="button" class="btn btn-success btn-sm bs-modal" data-form-url="{% url 'tidp:role-status-update' role.id %}" data-toggle="tooltip"> Change Status: {{role.get_status_display}} </button>
            {% endif %}
            </div>
          </div>

          {% if role.comment %}
              <p><span class="text-warning font-weight-bold"><u>Comment:</u></span> {{role.comment}} </p>
          {% endif %}

          <div class="table-responsive">
            <table class="table table-sm table-bordered">
              <thead class="thead-light">
                <tr>
                  <th>#</th>
                  <th>Description</th>
                  <th>Type</th>
                  <th>Unique Numbers</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for task in role.projecttask_set.all %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'tidp:task-detail' task.id %}">{{task.description}}</a> </td>
                    <td>{{task.task_type}} </td>
                    <td>{{ task.unique_code }} </td>
                    <td>
                      <a class="bs-modal" data-form-url="{% url 'tidp:projecttask-update' task.id %}" data-toggle="tooltip"><i class="fa fa-edit text-primary"></i></a>
                      <a class="bs-modal" data-form-url="{% url 'tidp:projecttask-delete' task.id %}" data-toggle="tooltip"><i class="fa fa-trash-alt text-danger"></i></a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% endfor %}


        {% if True %}
          <div class="text-center">
            <a class="btn btn-success" href="{% url 'tidp:generate-midp' project.id %}"><i class="fa fa-eye"></i> Generate MIDP</a>
            <a class="btn btn-info" href="{% url 'tidp:view-midp' project.id %}"><i class="fa fa-eye"></i> View MIDP</a>
          </div>
        {% endif %}


      {% else %}
        <p>There are currently no task for this project.</p>
      {% endif %}

    </div>
  </div>

  <!--Invite Task Leaders -->
  <div class="tab-pane fade" id="leaders" role="tabpanel" aria-labelledby="leaders-tab">
    <div class="mt-3">
      <button class="btn btn-primary bs-modal" type="button" data-form-url="{% url 'tidp:taskleader-create' project.id %}" data-toggle="tooltip">
        <i class="fas fa-plus"></i> Invite New Task Leader
      </button>
      {% if task_leaders %}
        <div class="table-responsive mt-2">
          <table class="table">
            <thead>
              <tr>
                <th>Contact Person</th>
                <th>Email Address</th>
                <th>Originator</th>
                <th>Roles</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for leader in task_leaders %}
                <tr>
                  <td>{{leader.contact_person}} </td>
                  <td>{{leader.contact_email}} </td>
                  <td>{{leader.company}} </td>
                  <td>{{leader.roles.all|join:", "}} </td>
                  <td>
                    <a class="bs-modal" data-form-url="{% url 'tidp:update-taskleader' leader.id %}" data-toggle="tooltip"><i class="fas fa-edit"></i></a>
                    <a class="bs-modal" data-form-url="{% url 'tidp:delete-taskleader' leader.id %}"><i class="fas fa-trash-alt text-danger"></i></a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <p>There are currently no task leader for this project</p>
      {% endif %}
    </div>
  </div>

  <!--Invite Task Members -->
  <div class="tab-pane fade" id="members" role="tabpanel" aria-labelledby="members-tab">
    <div class="mt-3">
      <button class="btn btn-primary bs-modal" type="button" data-form-url="{% url 'tidp:taskmember-create' project.id %}" data-toggle="tooltip">
        <i class="fas fa-plus"></i> Invite New Task Member
      </button>
      {% if task_members %}
        <div class="table-responsive mt-2">
          <table class="table">
            <thead>
              <tr>
                <th>Contact Person</th>
                <th>Email Address</th>
                <th>Originator</th>
                <th>Roles</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for member in task_members %}
                <tr>
                  <td>{{member.contact_person}} </td>
                  <td>{{member.contact_email}} </td>
                  <td>{{member.company}} </td>
                  <td>{{member.roles.all|join:", "}} </td>
                  <td>
                    <a class="bs-modal" data-form-url="{% url 'tidp:taskmember-update' member.id %}" data-toggle="tooltip"><i class="fas fa-edit"></i></a>
                    <a class="bs-modal" data-form-url="{% url 'tidp:taskmember-delete' member.id %}"><i class="fas fa-trash-alt text-danger"></i></a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <p>There are currently no task member for this project</p>
      {% endif %}
    </div>
  </div>



</div>


<div class="modal fade" role="dialog" id="modal" tabindex="-1">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

{% endblock content %}



{% block script %}
  <script type="text/javascript">
    $(document).ready(function() {
        $(".bs-modal").each(function () {
            $(this).modalForm({
                formURL: $(this).data('form-url')
            });
        });

    });
  </script>
{% endblock script %}

tidp/templates/tidp/project/project_form.html
{% extends "base.html" %}


{% block page-title %}
TIDP | Add new project
{% endblock page-title %}


{% block content %}

<form method="POST">
    {% csrf_token %}

    <div class="form-row">
      <div class="form-group col-md-6">
        {{form.name.label_tag}}
        {{form.name}}
      </div>
      <div class="form-group col-md-6">
        {{form.number.label_tag}}
        {{form.number}}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        {{form.code.label_tag}}
        {{form.code}}
      </div>
      <div class="form-group col-md-6">
        {{form.midp_tipd_template.label_tag}}
        {{form.midp_tipd_template}}
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        {{form.discipline.label_tag}}
        {{form.discipline}}
      </div>
      <div class="form-group col-md-6">
        {{form.discipline_category.label_tag}}
        {{form.discipline_category}}
      </div>

    </div>

    {{form.client.label_tag}}
    <div class="form-row align-items-center">
      <div class="col my-1">
        {{form.client}}
      </div>
      <div class="col-md-4 my-1">
        <a class="btn btn-primary btn-sm bs-modal" data-form-url="{% url 'tidp:create-company' %}?next={% url 'tidp:project-create' %}" data-toggle="tooltip">Add new company</button>
        </a>
      </div>
    </div>

    <button type="submit" class="mt-4 w-25 btn btn-primary float-right">Add new project</button>

  </form>


  <div class="modal fade" role="dialog" id="modal" tabindex="-1">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>


{% endblock %}



{% block script %}
  <script type="text/javascript">
    $(document).ready(function() {
        $(".bs-modal").each(function () {
            $(this).modalForm({
                formURL: $(this).data('form-url')
            });
        });

    });
  </script>
{% endblock script %}

tidp/templates/tidp/project/project_scales.html
{% extends "base.html" %}
{% load widget_tweaks %}


{% block page-title %}
TIDP | Project Scales
{% endblock page-title %}


{% block content %}

<form method="POST">
    {% csrf_token %}
    <div class="form-group form-row">
        <div class="col-sm-3">
          {{form.scale|add_class:"form-control"|attr:"placeholder:Scale"}}
        </div>
        <input type="submit" class="btn btn-primary" value="Add New Scale">
    </div>
</form>


    {% if projectscale %}
        <table class="table table-bordered">
            <thead>
                <th>Scale</th>
                <th></th>
            </thead>
            <tbody>
                {% for scale in projectscale %}
                    <tr>
                        <td>{{scale}} </td>
                        <td>
                            <a href="{% url 'tidp:project-scales-update' scale.id %}"><i class="fa fa-edit"></i></a>
                            <a href="{% url 'tidp:project-scales-delete' scale.id %}"><i class="fa fa-trash text-danger"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p>There are no scales yet.</p>
    {% endif %}

{% endblock %}