autobim/urls.py
from django.contrib import admin
from django.urls import path, include

from users.views import signin, signout
from home.views import dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', dashboard, name='home'),
    
    path('login/', signin, name='login'),
    path('logout/', signout, name='logout'),

    path('users/', include('users.urls')),
    path('design-check/', include('design_health.urls')),
    path('tidp/', include('tidp.urls')),
]

tidp/urls.py
from django.urls import path

from . import views

app_name = 'tidp'

urlpatterns = [
    path('roles/', views.role_list_view, name='roles'),
    path('roles/<int:pk>/update/', views.RoleUpdateView.as_view(), name="role-update"),
    path('roles/<int:pk>/delete/', views.RoleDeleteView.as_view(), name="role-delete"),

    path('company/list/', views.CompanyListView.as_view(),
       name='company-list'),
    path('company/create/', views.CompanyCreateView.as_view(),
        name='create-company'),
    path('company/<int:pk>/update/', views.CompanyUpdateView.as_view(), name="company-update"),
    path('company/<int:pk>/delete/', views.CompanyDeleteView.as_view(), name="company-delete"),

    path('projects/', views.ManageProjects.as_view(), name='projects'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project/<int:pk>/manage/', views.ProjectDetailView.as_view(), name='project-detail'),
    path('project/<int:pk>/lmanage/', views.ProjectDetailLeaderView.as_view(), name='project-detail-leader'),
    path('projects/<int:pk>/update/', views.ProjectUpdateView.as_view(), name='project-update'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('projects/submit-to-lead/', views.ProjectSubmitToLeadView.as_view(), name='project-submit-to-lead'),
    path('projects/role-status-update/<int:projectrole_id>/', views.RoleStatusUpdateView.as_view(), name='role-status-update'),

    path('project-discipline/', views.DisciplineListView.as_view(), name='project-discipline'),
    path('project-discipline/create/', views.DisciplineCreateView.as_view(), name='discipline-create'),
    path('discipline/<int:pk>/update/', views.DisciplineUpdateView.as_view(), name='update-discipline'),
    path('discipline/<int:pk>/delete/', views.DisciplineDeleteView.as_view(), name='delete-discipline'),

    path('discipline-categories/', views.DisciplineCategoryListView.as_view(), name='project-discipline-categories'),
    path('discipline-categories/create/', views.DisciplineCategoryCreateView.as_view(), name='discipline-category-create'),
    path('discipline-categories/<int:pk>/update/', views.DisciplineCategoryUpdateView.as_view(), name='update-discipline-category'),
    path('discipline-categories/<int:pk>/delete/', views.DisciplineCategoryDeleteView.as_view(), name='delete-discipline-category'),

    path('tasks/', views.TaskListView.as_view(), name='tasks'),
    path('tasks/create/', views.TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:pk>/update/', views.TaskUpdateView.as_view(), name="task-update"),
    path('tasks/<int:pk>/delete/', views.TaskDeleteView.as_view(), name="task-delete"),

    path('tasktype/', views.TaskTypeView.as_view(), name='tasktypes'),
    path('tasktype/create/', views.TaskTypeCreateView.as_view(), name='tasktype-create'),
    path('tasktype/<int:pk>/update/', views.TaskTypeUpdateView.as_view(), name="tasktype-update"),
    path('tasktype/<int:pk>/delete/', views.TaskTypeDeleteView.as_view(), name="tasktype-delete"),

    path('taskleader/<int:project_id>/create/', views.TaskLeaderCreateView.as_view(), name="taskleader-create"),
    path('taskleader/<int:pk>/update/', views.TaskLeaderUpdateView.as_view(), name="update-taskleader"),
    path('taskleader/<int:pk>/delete/', views.TaskLeaderDeleteView.as_view(), name="delete-taskleader"),

    path('taskmember/<int:project_id>/create/', views.TaskMemberCreateView.as_view(), name="taskmember-create"),
    path('taskmember/<int:pk>/update/', views.TaskMemberUpdateView.as_view(), name="taskmember-update"),
    path('taskmember/<int:pk>/delete/', views.TaskMemberDeleteView.as_view(), name="taskmember-delete"),

    path('export-tasks/<int:project_id>/<int:role>/', views.export_task_to_csv, name='export-tasks'),

    path('projecttask/<int:project_id>/<int:discipline>/<int:discipline_category>/<int:role>/<int:company>/create/', views.ProjectTaskCreateView.as_view(), name="projecttask-create"),

    path('projecttask-duplicate/', views.ProjectTaskDuplicateView.as_view(), name="projecttask-createmultiple"),

    path('projecttask/<int:pk>/update/', views.ProjectTaskUpdateView.as_view(), name="projecttask-update"),
    path('projecttask/<int:pk>/delete/', views.ProjectTaskDeleteView.as_view(), name="projecttask-delete"),
    path('tasks/<int:pk>/detail/', views.ProjectTaskDetailView.as_view(), name="task-detail"),

    path('roles/import/', views.import_roles, name='import-roles'),

    path('tasktype/import/', views.import_tasktypes, name='import-tasktypes'),

    path('projecttask/import/', views.import_tasks, name='import-projecttask'),

    path('projecttask/import/<int:project_id>/<int:role>/', views.import_project_task, name='import-projecttask-project'),

    path('get-company/', views.get_company, name='get-company'),
    path('get-disciplinecategory/', views.get_disciplinecategory, name='get-disciplinecategory'),

    path('mark-complete/<int:project_id>/<int:role_id>/<int:company_id>/', views.CompleteTaskPage.as_view(), name='mark-complete'),


    path('generate-tidp/<int:project_id>/<int:projectrole_id>/', views.GenerateTidpMidp.as_view(), name='generate-tidp'),
    path('generate-midp/<int:project_id>/', views.GenerateTidpMidp.as_view(), name='generate-midp'),

    path('view-tidp/<int:project_id>/<int:projectrole_id>/', views.ViewTidpMidp.as_view(), name='view-tidp'),
    path('view-midp/<int:project_id>/', views.ViewTidpMidp.as_view(), name='view-midp'),


    path('download-template/<content_type>/', views.download_exl_template, name='download-template'),

    path('project-scales', views.ProjectScaleView.as_view(), name='project-scales'),

    path('project-scales/<int:pk>/update/', views.ProjectScaleUpdateView.as_view(), name='project-scales-update'),

    path('project-scales/<int:pk>/delete/', views.ProjectScaleDeleteView.as_view(), name='project-scales-delete'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.index),
    path('delete/<int:id>/', views.delete, name='delete-user'),
    path('changepassword/', views.change_password, name='changepassword'),
    path('enable/<int:id>/', views.enable, name='enable-user'),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="AutoBIM">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>AutoBIM{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'dist/css/offcanvas.css' %}" rel="stylesheet">
    <link href="{% static 'dist/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'vendor/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}">
    {% block head %} {% endblock %}
  </head>
  <body class="bg-light">
    {% include 'menu.html' %}

    <main class="container">
      <div class="row">
        <div class="col">
          <div class="mt-3 mb-3 border-bottom">
            <h3>{% block page-title %}{% endblock page-title %}</h3>
          </div>

          {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </div>
              {% endfor %}
          {% endif %}

          {% block content %}
          {% endblock %}
        </div>
      </div>
    </main>

    <div class="footer border-top mt-4">
      <div class="container">
        <div class="mt-2 mb-4 text-center">
          <p>&copy; All rights reserved</p>
        </div>
      </div>
    </div>

    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <script src="{% static 'dist/js/offcanvas.js' %}"></script>
    <script src="{% static 'dist/js/custom.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>

    <script src="{% static 'vendor/select2/js/select2.full.min.js' %}"></script>

    <script>

      $(document).ready(function() {
        $('.custom-file-input').on('change',function(e){
            var fileName = document.getElementById(this.id).files[0].name;
            var nextSibling = e.target.nextElementSibling
            nextSibling.innerText = fileName
        })

        $(".bs-modal").each(function () {
            $(this).modalForm({
                formURL: $(this).data('form-url')
            });
        });
      });
    </script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>

    {% block script %}{% endblock %}

  </body>
</html>

templates/dashboard.html
{% extends "base.html" %}


{% block page-title %}
  Dashboard
{% endblock page-title %}
  

{% block content %}

<div class="row">
  <div class="col-6 col-sm-6 col-md-3">
    <div class="bloc">
      <span>PROJECTS</span>
      <h2>{{ number_of_projects }}</h2>
    </div>
  </div>
  <div class="col-6 col-sm-6 col-md-3">
    <div class="bloc">
      <span>TASKS</span>
      <h2>{{ number_of_tasks }}</h2>
    </div>
  </div>
  <div class="col-6 col-sm-6 col-md-3">
    <div class="bloc">
      <span>TASKS (DUE)</span>
      <h2>{{ number_of_due_tasks }}</h2>
    </div>
  </div>
  <div class="col-6 col-sm-6 col-md-3">
    <div class="bloc">
      <span>MIDP</span>
      <h2>{{ number_of_midps }}</h2>
    </div>
  </div>
</div>

{% endblock %}

templates/leader_dashboard.html
{% extends "base.html" %}


{% block page-title %}
  Dashboard
{% endblock page-title %}


{% block content %}


{% if projects_for_leader %}
  <p>Assigned Projects as a team leader</p>
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Client</th>
        <th>Number</th>
      </tr>
    </thead>
    <tbody>

      {% for project in projects_for_leader %}
        <tr class="clickable-row" data-href="{% url 'tidp:project-detail-leader' project.id %}">
          <td>{{project.name}} </td>
          <td>{{project.client}} </td>
          <td>{{project.number}} </td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
{% endif %}

{% if projects_for_member %}
  <p>Assigned Projects as a team member</p>
  <table class="table table-bordered table-hover">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Client</th>
        <th>Number</th>
      </tr>
    </thead>
    <tbody>

      {% for project in projects_for_member %}
        <tr class="clickable-row" data-href="{% url 'tidp:project-detail' project.id %}">
          <td>{{project.name}} </td>
          <td>{{project.client}} </td>
          <td>{{project.number}} </td>
        </tr>
      {% endfor %}

    </tbody>
  </table>
{% endif %}


{% endblock %}



{% block script %}
  <script>
    $(".clickable-row").click(function () {
      var pk = $(this).data("href")
      window.location = pk
    });
  </script>
{% endblock script %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AutoBIM</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="{% static 'dist/css/signin.css' %}" rel="stylesheet">
</head>
<body>
  
</body>
</html>
{% block content %}
  
  <form class="form-signin text-center" method="POST">  
    {% csrf_token %}
    <h1 class="h3 mb-3 font-weight-normal">AutoBIM <span class="small">by Leeds Beckett University</span></h1>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" name="email" placeholder="Email address" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Password" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2019</p>
  
  </form>
{% endblock %}

templates/menu.html
{% if user.is_superuser %}

<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
  <a class="navbar-brand mr-auto mr-lg-0" href="/">AutoBIM&nbsp;<span class="badge badge-warning">BETA</span></a>
  <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fa fa-home"></i>
          Dashboard </a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="tidp" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-book"></i>
              TIDP</a>
          <div class="dropdown-menu" aria-labelledby="tidp">
            <a class="dropdown-item" href="{% url 'tidp:projects' %}">Manage Projects</a>
            <a class="dropdown-item dropdown-toggle" href="#" id="tidpsettings" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Settings</a>
            <div class="dropdown-menu" aria-labelledby="tidpsettings">
              <a class="dropdown-item" href="{% url 'tidp:roles' %}">Roles</a>
              <a class="dropdown-item" href="{% url 'tidp:tasks' %}">Tasks</a>
              <a class="dropdown-item" href="{% url 'tidp:tasktypes' %}">Task Types</a>
              <a class="dropdown-item" href="{% url 'tidp:project-discipline' %}">Project Discipline </a>
              <a class="dropdown-item" href="{% url 'tidp:project-discipline-categories' %}">Discipline Categories</a>
              <a class="dropdown-item" href="{% url 'tidp:company-list' %}">Companies</a>
              <a class="dropdown-item" href="{% url 'tidp:project-scales' %}">Project Scales</a>
            </div>

          </div>
        </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="health-check-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-sync"></i>
            Design Model Health Check
        </a>
        <div class="dropdown-menu" aria-labelledby="health-check-menu">
          <a class="dropdown-item" href="{% url 'manage-projects' %}">Manage Projects</a>
          <a class="dropdown-item" href="{% url 'design-roles' %}">Roles/Responsibility</a>
          <a class="dropdown-item" href="{% url 'company-list' %}">Manage Companies</a>
          <a class="dropdown-item" href="{% url 'design-categories' %}">Design Categories</a>
          <a class="dropdown-item dropdown-toggle" href="#" id="heath-check-config-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Design Health Check Configuration
          </a>
          <div class="dropdown-menu" aria-labelledby="health-check-menu">
              <a class="dropdown-item" href="{% url 'concept-design' %}">Concept Design</a>
              <a class="dropdown-item" href="{% url 'developed-design' %}">Developed Design</a>
              <a class="dropdown-item" href="{% url 'technical-design' %}">Technical Design</a>
          </div>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="user-accounts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-user"></i>
              Accounts
        </a>
        <div class="dropdown-menu" aria-labelledby="user-accounts">
          <a class="dropdown-item" href="/users/">Users</a>
          <a class="dropdown-item" href="{% url 'users:changepassword' %}">Change Password</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>


{% else %}

<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
  <a class="navbar-brand mr-auto mr-lg-0" href="/">AutoBIM&nbsp;<span class="badge badge-warning">BETA</span></a>
  <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">
          <i class="fa fa-home"></i>
          Dashboard </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="user-accounts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fa fa-user"></i>
              Accounts
        </a>
        <div class="dropdown-menu" aria-labelledby="user-accounts">
          <a class="dropdown-item" href="{% url 'users:changepassword' %}">Change Password</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

{% endif %}

templates/paginator.html
{% load mytemplatetags %}

{% if page_obj and page_obj.paginator and page_obj.paginator.num_pages > 1 %}
  <nav aria-label="Result Pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' 1 %}"> &laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">previous</a></li>
        {% endif %}


        {% for item in page_obj.paginator.page_range %}

          {% if page_obj.number == item %}
            <li class="page-item active"><a class="page-link" href="#">{{item}} <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' item %}">{{item}}</a></li>
          {% endif %}


        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">next</a></li>
        <li class="page-item"><a class="page-link" href="?{% url_replace request 'page' page_obj.paginator.num_pages %}">Last &raquo;</a></li>
        {% endif %}
    </ul>
  </nav>
{% endif %}